## Arithmetic Functions

### Min and Max

In [ ]:
import numpy as np

var = np.array([1, 2, 3, 4, 5, 3, 2])

print("Min : ", np.min(var))
print("Max : ", np.max(var))

### Position

In [3]:
var = np.array([1, 2, 3, 4, 5, 3, 2])

print("Min : ", np.min(var))
print("Min Position :", np.argmin(var))

print("Max : ", np.max(var))
print("Max Position : ", np.argmax(var))

Min :  1
Min Position : 0
Max :  5
Max Position :  4


## 2D Array

In [7]:
var1 = np.array([[2, 1, 3], [9, 5, 6]])

print(np.min(var1, axis = 0))  # axis = 0 for column

[2 1 3]


In [9]:
var1 = np.array([[2, 1, 3], [9, 5, 6]])

print(np.min(var1, axis = 1))  # axis = 1 for Row

[1 5]


### Square root (sqrt)

In [10]:
import numpy as np

var = np.array([1, 2, 3, 4, 5, 3, 2])

print("Min : ", np.min(var))
print("Max : ", np.max(var))
print("sqrt : ", np.sqrt(var))

Min :  1
Max :  5
sqrt :  [1.         1.41421356 1.73205081 2.         2.23606798 1.73205081
 1.41421356]


### Sin and Cos 

In [12]:
var2 = np.array([1, 2, 3])

print(np.sin(var2))
print(np.cos(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


### Cummulative Sum (cumsum)

In [13]:
var3 = np.array([1, 2, 3])

print(np.cumsum(var3))

[1 3 6]
