## Broadcasting with numpy Array

In [1]:
import numpy as np

var1 = np.array([1, 2, 3])
print("Shape :", var1.shape)
print(var1)
print()

var2 = np.array([[1], [2], [3]])
print("Shape :", var2.shape)
print(var2)
print()

print(var1 + var2)

Shape : (3,)
[1 2 3]

Shape : (3, 1)
[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [2]:
x = np.array([[1], [2]])
print("Shape :", x.shape)
print(x)

print()

y = np.array([[1, 2, 3], [1, 2, 3]])
print("Shape :", y.shape)
print(y)

print()

print(x + y)

Shape : (2, 1)
[[1]
 [2]]

Shape : (2, 3)
[[1 2 3]
 [1 2 3]]

[[2 3 4]
 [3 4 5]]
