# Indexing

## 1D

In [1]:
import numpy as np
var = np.array([9, 8, 7, 6])
#               0, 1, 2, 3
#              -4,-3,-2,-1

print(var[1])
print(var[-3])

8
8


## 2D

In [2]:
var1 = np.array([[9, 8, 7], [4, 5, 6]])
print(var1)
print("Dimension :",var1.ndim)

print()

print(var1[0, 2])

[[9 8 7]
 [4 5 6]]
Dimension : 2

7


## 3D

In [3]:
var2 = np.array([[[1, 2], [6, 7]]])
print(var2)
print("Dimension :",var2.ndim)

print()

print(var2[0, 1, 1])

[[[1 2]
  [6 7]]]
Dimension : 3

7
