# Slicing

## 1D

In [1]:
import numpy as np
var = np.array([9, 8, 7, 6, 5, 4, 3])
            #   0, 1, 2, 3, 4, 5, 6
print(var)

print()

print("2 to 5 :", var[1:5])

print("2 to End :", var[1:])

print("Start to 5 :", var[:5])

print("Stop :", var[::2])

[9 8 7 6 5 4 3]

2 to 5 : [8 7 6 5]
2 to End : [8 7 6 5 4 3]
Start to 5 : [9 8 7 6 5]
Stop : [9 7 5 3]


## 2D

In [2]:
var1 = np.array([[1, 2, 3, 4, 5], [9, 8, 7, 6, 5], [11, 12, 13, 14, 15]])
        #         0, 1, 2, 3, 4    0, 1, 2, 3, 4     0, 1,  2,   3,  4 
print(var1)
print()

print("8 to 5 :", var1[2,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

8 to 5 : [12 13 14 15]


## 3D

In [5]:
var2 = np.array([[[1, 2, 3, 4, 5], [9, 8, 7, 6, 5], [11, 12, 13, 14, 15]]])
        #         0, 1, 2, 3, 4    0, 1, 2, 3, 4     0, 1,  2,   3,  4 
print(var2)
print()

print("8 to 5 :", var1[1,1:])

[[[ 1  2  3  4  5]
  [ 9  8  7  6  5]
  [11 12 13 14 15]]]

8 to 5 : [8 7 6 5]
