# Join Array

## 1D

In [2]:
import numpy as np
var = np.array([1, 2, 3, 4])
var1 = np.array([9, 8, 7, 6])

ar = np.concatenate((var, var1))
print(ar)

[1 2 3 4 9 8 7 6]


## 2D

In [3]:
vr = np.array([[1, 2], [3, 4]])
vr1 = np.array([[9, 8], [7, 6]])
print(vr)
print()
print(vr1)
print()

ar_new = np.concatenate((vr, vr1), axis = 0)
print(ar_new)

print()

ar_new1 = np.concatenate((vr, vr1), axis = 1)
print(ar_new1)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2]
 [3 4]
 [9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]


## np.stack() function

In [4]:
var_1 = np.array([1, 2, 3, 4])
var_2 = np.array([9, 8, 7, 6])

a_new = np.stack((var_1,var_2), axis = 1)
print(a_new)
print()

a_new1 = np.hstack((var_1,var_2)) #row
print(a_new1)
print()

a_new2 = np.vstack((var_1,var_2)) #column
print(a_new2)
print()

a_new3 = np.dstack((var_1,var_2)) #height
print(a_new3)
print()

[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]



# Split Array

## 1D

In [5]:
var = np.array([1, 2, 3, 4, 5, 6])
print(var)
print()

ar = np.array_split(var,3)
print(ar)
print(type(ar))
print(ar[0])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[1 2]


## 2D

In [6]:
var1 = np.array([[1, 2], [3, 4], [5, 6]])
print(var1)
print()

ar1 = np.array_split(var1,3)
print(ar1)
print()

ar2 = np.array_split(var1, 3, axis = 1)
print(ar2)

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]
