# Search, Search Sorted, Sort, Filter Array

## Search Array :- Search an array for a certain value and return the indexes that get a match

In [1]:
import numpy as np
var = np.array([1, 2, 3, 4, 2, 5, 2, 5, 6, 7])

x = np.where(var == 2)
print(x)

(array([1, 4, 6]),)


In [3]:
var = np.array([4, 2, 3, 4, 2, 5, 2, 5, 6, 7])

x = np.where((var % 2) == 0)
print(x)

(array([0, 1, 3, 4, 6, 8]),)


## Search Sorted Array :- it performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [4]:
var1 = np.array([1, 2, 3, 4, 6, 7, 8])

x1 = np.searchsorted(var1, 5)
print(x1)

4


In [5]:
var1 = np.array([1, 2, 3, 4, 9, 10])

x1 = np.searchsorted(var1, [5, 6, 7], side = "right")
print(x1)

[4 4 4]


## Sort Array :- Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

In [7]:
var_1 = np.array([4, 2, 3, 1, 12, 15, 22, 5, 52, 6, 7])

print(np.sort(var_1))

[ 1  2  3  4  5  6  7 12 15 22 52]


In [8]:
var_1 = np.array([[4, 2, 3], [1, 12, 15], [22, 5, 52]])

print(np.sort(var_1))

[[ 2  3  4]
 [ 1 12 15]
 [ 5 22 52]]


In [9]:
var_1 = np.array(["a", "s", "d", "f"])

print(np.sort(var_1))

['a' 'd' 'f' 's']


## Filter Array :- Getting some elements out of an existing array and creating a new array out of them.

In [10]:
var_2 = np.array(["a", "s", "d", "f"])

f = [True, False, False, True]
new_a = var_2[f]
print(new_a)
print(type(new_a))

['a' 'f']
<class 'numpy.ndarray'>
