# Shuffle, Unique, Resize, Flatten, Ravel Functions

## Shuffle

In [2]:
import numpy as np

var = np.array([1, 2, 3, 4, 5])

np.random.shuffle(var)

print(var)

[1 3 5 4 2]


## Unique

In [3]:
var1 = np.array([1, 2, 3, 4, 2, 5, 2, 6, 2, 7])

x = np.unique(var1)

print(x)

[1 2 3 4 5 6 7]


In [4]:
var1 = np.array([1, 2, 3, 4, 2, 5, 2, 6, 2, 7])

x = np.unique(var1, return_index = True, return_counts =True)

print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9]), array([1, 4, 1, 1, 1, 1, 1]))


## Resize

In [5]:
var2 = np.array([1, 2, 3, 4, 5, 6])

y = np.resize(var2, (3,2))

print(y)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
var2 = np.array([1, 2, 3, 4, 5, 6])

y = np.resize(var2, (2,3))

print(y)

[[1 2 3]
 [4 5 6]]


## Flatten & Ravel

In [8]:
var2 = np.array([1, 2, 3, 4, 5, 6])

y = np.resize(var2, (3,2))

print(y)
print()

print("Flatten : ", y.flatten(order = "F"))
print("Ravel : ", np.ravel(y, order = "K"))

[[1 2]
 [3 4]
 [5 6]]

Flatten :  [1 3 5 2 4 6]
Ravel :  [1 2 3 4 5 6]
