# Insert and Delete

## Insert

In [2]:
import numpy as np
var = np.array([1, 2, 3 ,4])
print(var)
v = np.insert (var, (2, 4), 40)
print(v)

[1 2 3 4]
[ 1  2 40  3  4 40]


#### Append function

In [5]:
var = np.array([1, 2, 3 ,4])
print(var)
x = np.append (var, 6.5)
print(x)

[1 2 3 4]
[1.  2.  3.  4.  6.5]


### 2D

In [3]:
var1 = np.array([[1, 2, 3], [1, 2, 3]])

v1 = np.insert(var1, 2, [25, 26], axis = 1)

print(v1)

[[ 1  2 25  3]
 [ 1  2 26  3]]


In [4]:
var1 = np.array([[1, 2, 3], [1, 2, 3]])

v1 = np.insert(var1, 2, [23, 24, 25], axis = 0)

print(v1)

[[ 1  2  3]
 [ 1  2  3]
 [23 24 25]]


#### Append function

In [6]:
var1 = np.array([[1, 2, 3], [1, 2, 3]])

v1 = np.append(var1, [[23, 24, 25]], axis = 0)

print(v1)

[[ 1  2  3]
 [ 1  2  3]
 [23 24 25]]


## Delete function

In [7]:
var2 = np.array([1, 2, 3 ,4])
print(var2)
d = np.delete(var2, 2)
print(d)

[1 2 3 4]
[1 2 4]
