# Matrix

## Array vs Matrix

In [1]:
import numpy as np
var = np.matrix([[1, 2, 3], [1, 2, 3]])
print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [2]:
var1 = np.array([[1, 2, 3], [1, 2, 3]])
print(var1)
print(type(var1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


## Arithmetic operation in matrix

### Addition 

In [3]:
var1 = np.matrix([[1, 2, 3], [1, 2, 3]])
print(var1)
print()
var2 = np.matrix([[1, 2, 3], [1, 2, 3]])
print(var1 + var2)

[[1 2 3]
 [1 2 3]]

[[2 4 6]
 [2 4 6]]


### Subtraction

In [4]:
var1 = np.matrix([[1, 2, 3], [1, 2, 3]])
print(var1)
print()
var2 = np.matrix([[1, 2, 3], [1, 2, 3]])
print(var1 - var2)

[[1 2 3]
 [1 2 3]]

[[0 0 0]
 [0 0 0]]


### Multiplication

In [7]:
var1 = np.matrix([[1, 2], [1, 2]])
print(var1)
print()
var2 = np.matrix([[1, 2], [1, 2]])
print(var1 * var2)
print()

print(var1.dot(var2))

[[1 2]
 [1 2]]

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]
