# Matrix Functions

## Transpose

In [1]:
import numpy as np
var = np.matrix([[1, 2, 3], [4, 5, 6]])
print(var)
print()

print(np.transpose(var))
print()

print(var.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


## Swapaxes

In [3]:
var1 = np.matrix([[1, 2, 3], [4, 5, 6]])
print(var1)
print()

print(np.swapaxes(var1, 0, 1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [5]:
var2 = np.matrix([[1, 2], [4, 5]])
print(var2)
print()

print(np.swapaxes(var2, 0, 1))

[[1 2]
 [4 5]]

[[1 4]
 [2 5]]


## Inverse

In [7]:
var3 = np.matrix([[1, 2], [3, 4]])
print(var3)
print()

print(np.linalg.inv(var3))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


## Power

In [9]:
var4 = np.matrix([[1, 2], [3, 4]])
print(var4)
print()

print(np.linalg.matrix_power(var4, 2))
print()

print(np.linalg.matrix_power(var4, 0))
print()

print(np.linalg.matrix_power(var4, -2))
print()

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



## Determinate

In [11]:
var5 = np.matrix([[1, 2], [3, 4]])
print(var5)
print()

print(np.linalg.det(var5))

[[1 2]
 [3 4]]

-2.0000000000000004


In [12]:
var6 = np.matrix([[1, 2, 3], [3, 4, 3], [1, 2, 3]])
print(var6)
print()

print(np.linalg.det(var6))

[[1 2 3]
 [3 4 3]
 [1 2 3]]

0.0
