# Zeros

In [12]:
import numpy as np

ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3, 4))

print(ar_zero)
print(ar_zero.ndim)
print()
print(ar_zero1)
print(ar_zero1.ndim)

[0. 0. 0. 0.]
1

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


# Ones

In [14]:
import numpy as np

ar_one = np.ones(4)
ar_one1 = np.ones((3,4))

print(ar_one)
print(ar_one.ndim)
print()
print(ar_one1)

[1. 1. 1. 1.]
1

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty

In [11]:
import numpy as np
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


# Range

In [15]:
import numpy as np
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


# Diagonal

In [16]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Linspace

In [17]:
ar_lin = np.linspace(0, 20, num = 5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]
