# Random

## rand() :- The function is used to generate a random value between 0 to 1.

In [1]:
import numpy as np

var = np.random.rand(4)

print(var)

[0.38597201 0.26980259 0.29434336 0.00440833]


In [2]:
var1 = np.random.rand(2, 5)

print(var1)

[[0.8912666  0.68768765 0.05803183 0.01533611 0.63697105]
 [0.24976163 0.18499674 0.85109717 0.69360403 0.77470453]]


## randn() :- The function is used to generate a random value close to zero. This may return positive or negative numbers as well.

In [4]:
var2 = np.random.randn(5)

print(var2)

[-0.00681143  1.18926243  0.02940295 -1.90220364 -1.14288941]


## ranf() :- The function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open interval[0.0, 1.0).

In [6]:
var3 = np.random.ranf(4)

print(var3)

[0.51597206 0.75168228 0.16273332 0.01531004]


## randint() :- The function is used to generate a random number between a given range.
            np.random.randint(min,max,total number)

In [9]:
var4 = np.random.randint(5,20,5)

print(var4)

[ 6  7 18 10 11]
