# Data Types

In [1]:
import numpy as np

var = np.array([1, 2, 3, 4, 12, 13, 14, 15])

print("Data Type :", var.dtype)

Data Type : int64


In [3]:
var = np.array([1.0, 1.2, 1.3])

print("Data Type :", var.dtype)

Data Type : float64


In [4]:
var = np.array(["A", "B", "C", "D"])

print("Data Type :", var.dtype)

Data Type : <U1


## Change data type

In [6]:
x = np.array([1, 2, 3, 4], dtype = np.int8)
print("Data Type :", x.dtype)
print(x)

Data Type : int8
[1 2 3 4]


In [7]:
x1 = np.array([1, 2, 3, 4], dtype = "f")
print("Data Type :", x1.dtype)
print(x1)

Data Type : float32
[1. 2. 3. 4.]


## Converting Data type using function

In [9]:
x2 = np.array([1, 2, 3, 4])

new = np.float32(x2)

print("Data type :", x2.dtype)
print("Data type :", new.dtype)

print(x2)
print(new)

Data type : int64
Data type : float32
[1 2 3 4]
[1. 2. 3. 4.]


In [10]:
x2 = np.array([1, 2, 3, 4])

new = np.float32(x2)
new_one = np.int_(new)

print("Data type :", x2.dtype)
print("Data type :", new.dtype)
print("Data type :", new_one.dtype)

print(x2)
print(new)
print(new_one)

Data type : int64
Data type : float32
Data type : int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [11]:
x3 = np.array([1, 2, 3, 4])
new_1 = x3.astype(float)
print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]
