## Arithmetic Operations

### Add

In [2]:
import numpy as np
var = np.array([1, 2, 3, 4])
varadd = var + 3
print(varadd)

[4 5 6 7]


In [3]:
var1 = np.array([1, 2, 3, 4])
var2 = np.array([1, 2, 3, 4])

varadd = var1 + var2

print(varadd)

[2 4 6 8]


In [5]:
var1 = np.array([1, 2, 3, 4])
var2 = np.array([1, 2, 3, 4])

varadd = np.add(var1, var2)

print(varadd)

[2 4 6 8]


In [7]:
var1 = np.array([1, 2, 3, 4])
var2 = np.array([1, 2, 3, 4])

varadd = np.add(var1, 3)

print(varadd)

[4 5 6 7]


#### 2D array

In [16]:
var2 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
var3 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

print(var2)
print("+")
print(var3)
print("=")

varadd2 = var2 + var3
print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]
+
[[1 2 3 4]
 [1 2 3 4]]
=
[[2 4 6 8]
 [2 4 6 8]]


### Subtraction

In [8]:
var = np.array([1, 2, 3, 4])
varadd = var - 3
print(varadd)

[-2 -1  0  1]


#### 2D Array

In [17]:
var2 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
var3 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

print(var2)
print("-")
print(var3)
print("=")

varadd2 = var2 - var3
print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]
-
[[1 2 3 4]
 [1 2 3 4]]
=
[[0 0 0 0]
 [0 0 0 0]]


### Multiply

In [9]:
var = np.array([1, 2, 3, 4])
varadd = var * 3
print(varadd)

[ 3  6  9 12]


#### 2D Array

In [18]:
var2 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
var3 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

print(var2)
print("*")
print(var3)
print("=")

varadd2 = var2 * var3
print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]
*
[[1 2 3 4]
 [1 2 3 4]]
=
[[ 1  4  9 16]
 [ 1  4  9 16]]


### Divide

In [10]:
var = np.array([1, 2, 3, 4])
varadd = var / 3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


#### 2D Array

In [19]:
var2 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
var3 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

print(var2)
print("/")
print(var3)
print("=")

varadd2 = var2 / var3
print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]
/
[[1 2 3 4]
 [1 2 3 4]]
=
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Mod

In [11]:
var = np.array([1, 2, 3, 4])
varadd = var % 3
print(varadd)

[1 2 0 1]


#### 2D Array

In [20]:
var2 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
var3 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

print(var2)
print("%")
print(var3)
print("=")

varadd2 = var2 % var3
print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]
%
[[1 2 3 4]
 [1 2 3 4]]
=
[[0 0 0 0]
 [0 0 0 0]]


### Power

In [12]:
var = np.array([1, 2, 3, 4])
varadd = var ** 3
print(varadd)

[ 1  8 27 64]


#### 2D Array

In [21]:
var2 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
var3 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

print(var2)
print("**")
print(var3)
print("=")

varadd2 = var2 ** var3
print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]
**
[[1 2 3 4]
 [1 2 3 4]]
=
[[  1   4  27 256]
 [  1   4  27 256]]


### Reciprocal

In [22]:
var = np.array([1, 2, 3, 4])
varadd = np.reciprocal(var)
print(varadd)

[1 0 0 0]
